#
# Label definitions
#

common: &common
  bug: "ee0701"
  "bug/sporadic test failure": "ee0701"
  changelog/yes: "d4c5f9"
  changelog/no: "d4c5f9"
  cleanup: "fef2c0"
  dependencies: "b4a8d1"
  developer: "bcf5db"
  documentation: "d4c5f9"
  duplicate: "eeeeee"
  enhancement: "84b6eb"
  "good first issue": "0e8a16"
  hacktoberfest: "ff7619"
  "help wanted": "0e8a16"
  internationalization: "d4c5f9"
  notabug: "eeeeee"
  performance: "e99695"
  pinned: "eeeeee"
  question: "cc317c"
  refactoring: "fbca04"
  redesign: "e99695"
  "size/l": "0e8a16"
  "size/m": "0e8a16"
  "size/s": "0e8a16"
  "size/xl": "0e8a16"
  stale: "eeeeee"
  "technical debt": "ff7619"
  test: "bfe5bf"
  tools: "bcf5db"
  unmergeable: "eeeeee"
  verified: "0e8a16"
  wip: "eeeeee"
  wontfix: "eeeeee"

semver: &semver
  "needs major version": "6a92bc"
  "needs minor version": "6a92bc"

provider_plugin: &provider_plugin
  events: "5319e7"
  inventory: "5319e7"
  metrics: "5319e7"
  operations: "5319e7"
  "smart state": "5319e7"

provider_types: &provider_types
  providers/automation: "5319e7"
  providers/cloud: "5319e7"
  providers/configuration: "5319e7"
  providers/containers: "5319e7"
  providers/middleware: "5319e7"
  providers/network: "5319e7"
  providers/physical: "5319e7"
  providers/provisioning: "5319e7"
  providers/storage: "5319e7"
  providers/virtual: "5319e7"

ux: &ux
  ux/review: "cc317c"
  ux/approved: "0e8a16"

v2v: &v2v
  v2v: "5319e7"

#
# Release label definitions
#

release: &release
  blocker: "000000"
  "bugzilla needed": "000000"

release_lasker: &release_lasker
  lasker/yes: "000000"
  lasker/yes?: "000000"
  lasker/no: "000000"
  lasker/backported: "000000"
  lasker/conflict: "000000"

release_kasparov: &release_kasparov
  kasparov/yes: "555555"
  kasparov/yes?: "555555"
  kasparov/no: "555555"
  kasparov/backported: "555555"
  kasparov/conflict: "555555"

release_jansa: &release_jansa
  jansa/yes: "dddddd"
  jansa/yes?: "dddddd"
  jansa/no: "dddddd"
  jansa/backported: "dddddd"
  jansa/conflict: "dddddd"

release_ivanchuk: &release_ivanchuk
  ivanchuk/yes: "dddddd"
  ivanchuk/no: "dddddd"
  ivanchuk/backported: "dddddd"
  ivanchuk/conflict: "dddddd"

release_hammer: &release_hammer
  hammer/yes: "dddddd"
  hammer/no: "dddddd"
  hammer/backported: "dddddd"
  hammer/conflict: "dddddd"

release_gaprindashvili: &release_gaprindashvili
  gaprindashvili/yes: "dddddd"
  gaprindashvili/no: "dddddd"
  gaprindashvili/backported: "dddddd"
  gaprindashvili/conflict: "dddddd"

release_fine: &release_fine
  fine/yes: "dddddd"
  fine/no: "dddddd"
  fine/backported: "dddddd"
  fine/conflict: "dddddd"

release_euwe: &release_euwe
  euwe/yes: "dddddd"
  euwe/no: "dddddd"
  euwe/backported: "dddddd"
  euwe/conflict: "dddddd"

release_darga: &release_darga
  darga/yes: "dddddd"
  darga/no: "dddddd"
  darga/backported: "dddddd"
  darga/conflict: "dddddd"

feature_introduced_in_darga_or_prior: &feature_introduced_in_darga_or_prior
  <<: *release_darga
  <<: *release_euwe
  <<: *release_fine
  <<: *release_gaprindashvili
  <<: *release_hammer
  <<: *release_ivanchuk
  <<: *release_jansa
  <<: *release_kasparov
  <<: *release_lasker

feature_introduced_in_euwe: &feature_introduced_in_euwe
  <<: *release_euwe
  <<: *release_fine
  <<: *release_gaprindashvili
  <<: *release_hammer
  <<: *release_ivanchuk
  <<: *release_jansa
  <<: *release_kasparov
  <<: *release_lasker

feature_introduced_in_fine: &feature_introduced_in_fine
  <<: *release_fine
  <<: *release_gaprindashvili
  <<: *release_hammer
  <<: *release_ivanchuk
  <<: *release_jansa
  <<: *release_kasparov
  <<: *release_lasker

feature_introduced_in_gaprindashvili: &feature_introduced_in_gaprindashvili
  <<: *release_gaprindashvili
  <<: *release_hammer
  <<: *release_ivanchuk
  <<: *release_jansa
  <<: *release_kasparov
  <<: *release_lasker

feature_introduced_in_hammer: &feature_introduced_in_hammer
  <<: *release_hammer
  <<: *release_ivanchuk
  <<: *release_jansa
  <<: *release_kasparov
  <<: *release_lasker

feature_introduced_in_ivanchuk: &feature_introduced_in_ivanchuk
  <<: *release_ivanchuk
  <<: *release_jansa
  <<: *release_kasparov
  <<: *release_lasker

feature_introduced_in_jansa: &feature_introduced_in_jansa
  <<: *release_jansa
  <<: *release_kasparov
  <<: *release_lasker

feature_introduced_in_kasparov: &feature_introduced_in_kasparov
  <<: *release_kasparov
  <<: *release_lasker

feature_introduced_in_lasker: &feature_introduced_in_lasker
  <<: *release_lasker

#
# Label Assignments
#

orgs:
  ManageIQ:
    except:
    - ManageIQ/integration_tests
    - ManageIQ/integration_tests_playbooks
    - ManageIQ/miq_tools_services
    - ManageIQ/polisher
    labels:
      <<: *common

repos:
  ManageIQ/container-amazon-smartstate:
    <<: *common
    <<: *feature_introduced_in_hammer
    <<: *release
  ManageIQ/manageiq:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *provider_types
    <<: *release
    <<: *v2v
  ManageIQ/manageiq-api:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *provider_types
    <<: *release
    <<: *semver
  ManageIQ/manageiq-appliance:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *release
  ManageIQ/manageiq-appliance-build:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *release
  ManageIQ/manageiq-automation_engine:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *release
    <<: *v2v
  ManageIQ/manageiq-consumption:
    <<: *common
    <<: *feature_introduced_in_gaprindashvili
    <<: *release
  ManageIQ/manageiq-content:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *provider_types
    <<: *release
    <<: *v2v
  ManageIQ/manageiq-documentation:
    <<: *feature_introduced_in_darga_or_prior
    <<: *release
  ManageIQ/manageiq-gems-pending:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *release
  ManageIQ/manageiq-graphql:
    <<: *common
    <<: *feature_introduced_in_hammer
    <<: *release
  ManageIQ/manageiq-pods:
    <<: *common
    <<: *feature_introduced_in_fine
    <<: *release
  ManageIQ/manageiq-providers-amazon:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *provider_plugin
    <<: *release
  ManageIQ/manageiq-providers-ansible_tower:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *provider_plugin
    <<: *release
  ManageIQ/manageiq-providers-autosde:
    <<: *common
    <<: *feature_introduced_in_kasparov
    <<: *provider_plugin
    <<: *release
  ManageIQ/manageiq-providers-azure:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *provider_plugin
    <<: *release
  ManageIQ/manageiq-providers-azure_stack:
    <<: *common
    <<: *feature_introduced_in_ivanchuk
    <<: *provider_plugin
    <<: *release
  ManageIQ/manageiq-providers-foreman:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *provider_plugin
    <<: *release
  ManageIQ/manageiq-providers-google:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *provider_plugin
    <<: *release
  ManageIQ/manageiq-providers-ibm_cloud:
    <<: *common
    <<: *feature_introduced_in_kasparov
    <<: *provider_plugin
    <<: *release
  ManageIQ/manageiq-providers-ibm_terraform:
    <<: *common
    <<: *feature_introduced_in_kasparov
    <<: *provider_plugin
    <<: *release
  ManageIQ/manageiq-providers-kubernetes:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *provider_plugin
    <<: *release
  ManageIQ/manageiq-providers-kubevirt:
    <<: *common
    <<: *feature_introduced_in_hammer
    <<: *provider_plugin
    <<: *release
  ManageIQ/manageiq-providers-lenovo:
    <<: *common
    <<: *feature_introduced_in_fine
    <<: *provider_plugin
    <<: *release
  ManageIQ/manageiq-providers-nsxt:
    <<: *common
    <<: *feature_introduced_in_kasparov
    <<: *provider_plugin
    <<: *release
  ManageIQ/manageiq-providers-nuage:
    <<: *common
    <<: *feature_introduced_in_euwe
    <<: *provider_plugin
    <<: *release
  ManageIQ/manageiq-providers-openshift:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *provider_plugin
    <<: *release
  ManageIQ/manageiq-providers-openstack:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *provider_plugin
    <<: *release
  ManageIQ/manageiq-providers-ovirt:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *provider_plugin
    <<: *release
  ManageIQ/manageiq-providers-redfish:
    <<: *common
    <<: *feature_introduced_in_hammer
    <<: *provider_plugin
    <<: *release
  ManageIQ/manageiq-providers-scvmm:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *provider_plugin
    <<: *release
  ManageIQ/manageiq-providers-vmware:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *provider_plugin
    <<: *release
  ManageIQ/manageiq-rpm_build:
    <<: *common
    <<: *feature_introduced_in_jansa
    <<: *release
  ManageIQ/manageiq-schema:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *provider_types
    <<: *release
    <<: *v2v
  ManageIQ/manageiq-ui-classic:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *release
    <<: *ux
    <<: *v2v
  ManageIQ/manageiq-ui-service:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *release
    <<: *ux
  ManageIQ/manageiq-v2v:
    <<: *common
    <<: *feature_introduced_in_gaprindashvili
    <<: *release
    <<: *ux
    <<: *v2v
  #
  # Released gems and packages
  #
  ansible/ansible_tower_client_ruby:
    <<: *common
    <<: *semver
  ManageIQ/dbus_api_service:
    <<: *common
    <<: *release
    <<: *semver
  ManageIQ/httpd_configmap_generator:
    <<: *common
    <<: *release
    <<: *semver
  ManageIQ/inventory_refresh:
    <<: *common
    <<: *semver
  ManageIQ/log_decorator:
    <<: *common
    <<: *semver
  ManageIQ/manageiq-appliance_console:
    <<: *common
    <<: *release
    # Starting with gaprindashvili, there are no more backports, so this backport list is hardcoded
    <<: *release_darga
    <<: *release_euwe
    <<: *release_fine
    <<: *semver
  ManageIQ/manageiq-messaging:
    <<: *common
    <<: *semver
  ManageIQ/manageiq-smartstate:
    <<: *common
    <<: *release
    # Starting with gaprindashvili, there are no more backports, so this backport list is hardcoded
    <<: *release_darga
    <<: *release_euwe
    <<: *release_fine
    <<: *semver
  ManageIQ/ui-components:
    <<: *common
    <<: *semver
    <<: *ux
