common: &common
  bug: "ee0701"
  "bug/sporadic test failure": "ee0701"
  changelog/yes: "d4c5f9"
  changelog/no: "d4c5f9"
  cleanup: "fef2c0"
  dependencies: "b4a8d1"
  developer: "bcf5db"
  documentation: "d4c5f9"
  duplicate: "eeeeee"
  enhancement: "84b6eb"
  hacktoberfest: "ff7619"
  "help wanted": "0e8a16"
  internationalization: "d4c5f9"
  notabug: "eeeeee"
  performance: "e99695"
  pinned: "eeeeee"
  question: "cc317c"
  refactoring: "fbca04"
  redesign: "e99695"
  stale: "eeeeee"
  "technical debt": "ff7619"
  test: "bfe5bf"
  tools: "bcf5db"
  unmergeable: "eeeeee"
  verified: "0e8a16"
  wip: "eeeeee"
  wontfix: "eeeeee"

release: &release
  blocker: "000000"
  "bugzilla needed": "000000"

release_jansa: &release_jansa
  jansa/yes: "000000"
  jansa/yes?: "000000"
  jansa/no: "000000"
  jansa/backported: "000000"
  jansa/conflict: "000000"

release_ivanchuk: &release_ivanchuk
  ivanchuk/yes: "555555"
  ivanchuk/no: "555555"
  ivanchuk/backported: "555555"
  ivanchuk/conflict: "555555"

release_hammer: &release_hammer
  hammer/yes: "dddddd"
  hammer/no: "dddddd"
  hammer/backported: "dddddd"
  hammer/conflict: "dddddd"

release_gaprindashvili: &release_gaprindashvili
  gaprindashvili/yes: "dddddd"
  gaprindashvili/no: "dddddd"
  gaprindashvili/backported: "dddddd"
  gaprindashvili/conflict: "dddddd"

release_fine: &release_fine
  fine/yes: "dddddd"
  fine/no: "dddddd"
  fine/backported: "dddddd"
  fine/conflict: "dddddd"

release_euwe: &release_euwe
  euwe/yes: "dddddd"
  euwe/no: "dddddd"
  euwe/backported: "dddddd"
  euwe/conflict: "dddddd"

release_darga: &release_darga
  darga/yes: "dddddd"
  darga/no: "dddddd"
  darga/backported: "dddddd"
  darga/conflict: "dddddd"

feature_introduced_in_darga_or_prior: &feature_introduced_in_darga_or_prior
  <<: *release_darga
  <<: *release_euwe
  <<: *release_fine
  <<: *release_gaprindashvili
  <<: *release_hammer
  <<: *release_ivanchuk
  <<: *release_jansa

feature_introduced_in_euwe: &feature_introduced_in_euwe
  <<: *release_euwe
  <<: *release_fine
  <<: *release_gaprindashvili
  <<: *release_hammer
  <<: *release_ivanchuk
  <<: *release_jansa

feature_introduced_in_fine: &feature_introduced_in_fine
  <<: *release_fine
  <<: *release_gaprindashvili
  <<: *release_hammer
  <<: *release_ivanchuk
  <<: *release_jansa

feature_introduced_in_gaprindashvili: &feature_introduced_in_gaprindashvili
  <<: *release_gaprindashvili
  <<: *release_hammer
  <<: *release_ivanchuk
  <<: *release_jansa

feature_introduced_in_hammer: &feature_introduced_in_hammer
  <<: *release_hammer
  <<: *release_ivanchuk
  <<: *release_jansa

feature_introduced_in_ivanchuk: &feature_introduced_in_ivanchuk
  <<: *release_ivanchuk
  <<: *release_jansa

feature_introduced_in_jansa: &feature_introduced_in_jansa
  <<: *release_jansa

semver: &semver
  "needs major version": "6a92bc"
  "needs minor version": "6a92bc"

provider_plugin: &provider_plugin
  events: "5319e7"
  inventory: "5319e7"
  metrics: "5319e7"
  operations: "5319e7"
  "smart state": "5319e7"

provider_types: &provider_types
  providers/automation: "5319e7"
  providers/cloud: "5319e7"
  providers/configuration: "5319e7"
  providers/containers: "5319e7"
  providers/middleware: "5319e7"
  providers/network: "5319e7"
  providers/physical: "5319e7"
  providers/provisioning: "5319e7"
  providers/storage: "5319e7"
  providers/virtual: "5319e7"

ux: &ux
  ux/review: "cc317c"
  ux/approved: "0e8a16"

v2v: &v2v
  v2v: "5319e7"

repos:
  manageiq:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *provider_types
    <<: *release
    <<: *v2v
  manageiq-api:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *provider_types
    <<: *release
    <<: *semver
  manageiq-appliance:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *release
  manageiq-appliance-build:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *release
  manageiq-automation_engine:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *release
    <<: *v2v
  manageiq-consumption:
    <<: *common
    <<: *feature_introduced_in_gaprindashvili
    <<: *release
  manageiq-content:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *provider_types
    <<: *release
    <<: *v2v
  manageiq-gems-pending:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *release
  manageiq-graphql:
    <<: *common
    <<: *feature_introduced_in_hammer
    <<: *release
  manageiq-pods:
    <<: *common
    <<: *feature_introduced_in_fine
    <<: *release
  manageiq-providers-amazon:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *provider_plugin
    <<: *release
  manageiq-providers-ansible_tower:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *provider_plugin
    <<: *release
  manageiq-providers-azure:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *provider_plugin
    <<: *release
  manageiq-providers-azure_stack:
    <<: *common
    <<: *feature_introduced_in_ivanchuk
    <<: *provider_plugin
    <<: *release
  manageiq-providers-foreman:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *provider_plugin
    <<: *release
  manageiq-providers-google:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *provider_plugin
    <<: *release
  manageiq-providers-hawkular:
    <<: *common
    # Starting with hammer, there are no more backports, so this backport list is hardcoded
    <<: *release_darga
    <<: *release_euwe
    <<: *release_fine
    <<: *release_gaprindashvili
    <<: *provider_plugin
    <<: *release
  manageiq-providers-kubernetes:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *provider_plugin
    <<: *release
  manageiq-providers-kubevirt:
    <<: *common
    <<: *feature_introduced_in_hammer
    <<: *provider_plugin
    <<: *release
  manageiq-providers-lenovo:
    <<: *common
    <<: *feature_introduced_in_fine
    <<: *provider_plugin
    <<: *release
  manageiq-providers-nsxt:
    <<: *common
    <<: *provider_plugin
    <<: *release
  manageiq-providers-nuage:
    <<: *common
    <<: *feature_introduced_in_euwe
    <<: *provider_plugin
    <<: *release
  manageiq-providers-openshift:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *provider_plugin
    <<: *release
  manageiq-providers-openstack:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *provider_plugin
    <<: *release
  manageiq-providers-ovirt:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *provider_plugin
    <<: *release
  manageiq-providers-redfish:
    <<: *common
    <<: *feature_introduced_in_hammer
    <<: *provider_plugin
    <<: *release
  manageiq-providers-scvmm:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *provider_plugin
    <<: *release
  manageiq-providers-vmware:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *provider_plugin
    <<: *release
  manageiq-schema:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *provider_types
    <<: *release
    <<: *v2v
  manageiq-ui-classic:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *release
    <<: *ux
    <<: *v2v
  manageiq-ui-service:
    <<: *common
    <<: *feature_introduced_in_darga_or_prior
    <<: *release
    <<: *ux
  manageiq-v2v:
    <<: *common
    <<: *feature_introduced_in_gaprindashvili
    <<: *release
    <<: *ux
    <<: *v2v
  manageiq_docs:
    <<: *release
  #
  # Released gems and packages
  #
  dbus_api_service:
    <<: *common
    <<: *release
    <<: *semver
  httpd_configmap_generator:
    <<: *common
    <<: *release
    <<: *semver
  inventory_refresh:
    <<: *common
    <<: *semver
  log_decorator:
    <<: *common
    <<: *semver
  manageiq-appliance_console:
    <<: *common
    <<: *release
    # Starting with gaprindashvili, there are no more backports, so this backport list is hardcoded
    <<: *release_darga
    <<: *release_euwe
    <<: *release_fine
    <<: *semver
  manageiq-messaging:
    <<: *common
    <<: *semver
  manageiq-smartstate:
    <<: *common
    <<: *release
    # Starting with gaprindashvili, there are no more backports, so this backport list is hardcoded
    <<: *release_darga
    <<: *release_euwe
    <<: *release_fine
    <<: *semver
  ui-components:
    <<: *common
    <<: *semver
    <<: *ux
