topological-stable:
  RedHatInsights/topological_inventory-amazon:
  RedHatInsights/topological_inventory-ansible_tower:
  RedHatInsights/topological_inventory-api:
  RedHatInsights/topological_inventory-azure:
  RedHatInsights/topological_inventory-core:
  RedHatInsights/topological_inventory-ingress_api:
  RedHatInsights/topological_inventory-openshift:
  RedHatInsights/topological_inventory-orchestrator:
  RedHatInsights/topological_inventory-persister:
  RedHatInsights/topological_inventory-providers-common:
  RedHatInsights/topological_inventory-satellite:
  RedHatInsights/topological_inventory-scheduler:
  RedHatInsights/topological_inventory-sync:
