topological-stable:
  topological_inventory-amazon:
  topological_inventory-ansible_tower:
  topological_inventory-api:
  topological_inventory-azure:
  topological_inventory-core:
  topological_inventory-host_inventory_sync:
  topological_inventory-ingress_api:
  topological_inventory-openshift:
  topological_inventory-orchestrator:
  topological_inventory-persister:
  topological_inventory-providers-common:
  topological_inventory-satellite:
  topological_inventory-sync:
